CD-grid stress arrays
apcraig/CICE pull request #28
Opened 2021-11-18 22:23 UTC by phil-blain

to be discussed... I tried grepping 'stressp_1' and added the new arrays where I thought they were needed... I'll clean up the commit history tomorrow. Probably missing some stuff

2021-11-18 22:49 UTC, eclare108213 reviewed
Looks good so far.  Thanks for implementing these arrays in the restart files!

2021-11-18 22:57 UTC, dabail10 commented on cicecore/cicedynB/analysis/ice_history.F90
> +            case('CD')
Why is there an extra case('CD') here?

2021-11-18 22:59 UTC, dabail10 commented on cicecore/cicedynB/general/ice_flux.F90
>           stress12_1,stress12_2,stress12_3,stress12_4    ! sigma12
This line needs a comma and ampersand.

2021-11-18 23:02 UTC, dabail10 requested changes
This is looking really good. There might be some syntax errors beyond the one that github actions failed on.

2021-11-19 14:55 UTC, phil-blain commented on cicecore/cicedynB/analysis/ice_history.F90
> +            case('CD')
fixed.

2021-11-19 14:55 UTC, phil-blain commented on cicecore/cicedynB/general/ice_flux.F90
>           stress12_1,stress12_2,stress12_3,stress12_4    ! sigma12
also fixed

2021-11-19 14:56 UTC, phil-blain commented
Yeah I pushed that without even compiling (!). I compiles now, I'll update the PR soon.

2021-11-19 16:03 UTC, phil-blain commented
I cleaned up the compile failures, and cleaned up the commit history.

There are ~two~ three TODOs that maybe we will want to discuss..

2021-11-19 16:30 UTC, phil-blain commented on cicecore/cicedynB/infrastructure/ice_restart_driver.F90
> +         ! TODO: CD-grid ?
These initialization date from https://github.com/CICE-Consortium/CICE-svn-trunk/commit/788626f9

2021-11-19 16:32 UTC, dabail10 approved these changes

2021-11-19 16:33 UTC, apcraig approved these changes

2021-11-19 16:35 UTC, eclare108213 approved these changes

2021-11-19 16:35 UTC, merged